kind: ENC[AES256_GCM,data:ViB2ZJAg,iv:u3L7iuhJPyQrHFkDJaA4fN0i35kBdotDWPkN8XWvEZc=,tag:CRXYV1UztZNKK+Nsp3HLmA==,type:str]
ansible_user: ENC[AES256_GCM,data:p4D8yg==,iv:ft5OyLZOPrPTj/TZ/q3DQQvo6rZUjRwB/9ATfDd/OGg=,tag:6/zl7QcThNhbDue72Ax6fw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WVKJLg==,iv:Czw+0MXOpt+9hq/ZsB7pfMtgl0XyT3oQAVWi39Wjftc=,tag:PumtyAW6QZ8xAx7gQ16a3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWVZXblVadFp5UFVzci90
            WlFPQ2FUUm5Na3Zmek1tTDBEdUpMTXRDTEVNCmh2MVZtUzk5K1dBTTNBWEFjMjgv
            ZkZuMHh3Tk5hZWViZkZ3Y1BKb0NTN1EKLS0tIGwxeVFwMFBwWEpYRUZ4bTFGZUNh
            Rm9lZGpqcEV4SUR0cHlmTFh6NVliUkkKkiWkCw5kSK/WArY+uYN/5efn3vjYEj0q
            +jk0R7/Gr60mXnf/d8gqsgpjlZmWeWjvRN77aw50vf4P73fPwNO4Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T10:22:21Z"
    mac: ENC[AES256_GCM,data:ms8qaGWtDljmkyt8Z1pIv0/JYP8ye/uiw3NkA4ASHmJfYLtT38CoG5Zr41gXNcA6+ZpaWtI4w2znDWbkBKIaF+7gH2D8QCc3t6zt374ZczGLAU968zVHWyFd/Wz1pjJlACv7sfPc4VerAeT9nDq2GO2hl0U2yLOzSnzkkyw9MZE=,iv:BCaXHIlRtUFfv3TGGBX3/FaHTrBHR7rtyjm1RRjxk+4=,tag:8DWdm+pyN0PEE5cSyafylQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
