kind: ENC[AES256_GCM,data:MQ7gUhct,iv:2Z4H5INksQLN5DR8IDiI9aQlClWVhM8w5PmIPO3caFw=,tag:4OK0aF4hRMzOU41vGSU6YQ==,type:str]
ansible_user: ENC[AES256_GCM,data:GyQjFw==,iv:OYTcR5LKFK2hX5PvPqhv96nI73UvBoKNulmUszjwb+w=,tag:RQ39xzaSYVLquaHxNjjB1A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:u5pNqA==,iv:1/KUzYTFuOcnHOwY8SY8QXW60yWrO3w881L3bKKH8JY=,tag:2Q2Jae4te2ZBxQDfbROHXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTWNzU25QV0NrdzFhRE1Z
            MjhhQituVEZ3WWlWQnVabm5GZmlDU0NKYWpFCkpaV05JUDBxK0ZYeWFoTW9hYklK
            QzNmSzVhL1MyN1VLVi81TW5VaGJzSzgKLS0tIHJTOUIycytnRFNldE5wR042ZTZ5
            R2p0K2JGemZZQVhWQ1AyaVA5ZGdZN2sKZNxO2ceU6+3VBxFVGpppkFzwWfNfkzAH
            tQC5HBw2A5dg+f5GrBIjgPGtApvUutgZ3u8cti/42KfXEYrFLDOVOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T10:22:21Z"
    mac: ENC[AES256_GCM,data:uU4yRL69aAxf56FB3Y69k8lGhsD22ex+Xh5dSQ033ndkZBoxyGy2ltS/AxLCWAfobOuSBTv1nLsj6d7ORAldtA7DMH9m7z+tlQzLWo9SZIjeDuqflOM94b4IHsUqffxoZxNy8NUffOvRPKKQhQ/qyLtmXf0IEe2rX6pzNLyTVh4=,iv:GKuc2XW0jEk+vstNs8dVEECi7JZtGjdeZRR0kKPUP0I=,tag:RxzItVJlqrMaqBAvu3h7Og==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
