kind: ENC[AES256_GCM,data:VXXhagVW,iv:tAuKPhhH+f9tCAPgpw0Xi8mclc4vPDOmhQEh/0SsVJU=,tag:cvSJFrEK4EWq4CVJKUaPdw==,type:str]
ansible_user: ENC[AES256_GCM,data:f25XVg==,iv:CJ7j+wBv8FgAVSZJ4BFnJXV4X/95P0B8UY47fd4ce9w=,tag:b9OQac+JSFK+a+dyyd8tDQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:+O1wcg==,iv:0eDI8Vv6HNzIZbQyVg2Lq/GTW3+y4yzniypmeQh9rfM=,tag:Oe+hGO9gPdHATerhAwYkJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaXJtMGtTU1RJbWNuWTVR
            RWRNaTFFODFkTnpGaW83dllXZGx0Zkx2ZG0wClRaTnhoQy9keTRteG81S3IvZVhQ
            cXkvR3UxYThHOVdIeWpGbzFUdlc3Z28KLS0tIEhySGFRRElvb282OXphd2FUblVZ
            ejIwU0plczU0V2Y3anE4WU0wNUZoY2MKsQPZWyqz8XYm3cZbplpZX6kftSxFPrMW
            tIzRFAecwfLpkl1lWoMa7eoW3f2cd4sXtxI8544BLyVt5/3w+k/ZPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T10:22:21Z"
    mac: ENC[AES256_GCM,data:6GgVnXPewsIwN/lQZB2R2TS+SqjdJF1O2lhYZvOUmLEAdodIq28IIVctXipCbRGyIiH/k9aw43acHq+iE/ywQluBrKaGZySWlEUUjHDn4CgMN43kppf5EzMl1ec7LcpOvBjtUtWJudHzW2AKAKzzyLYn1Hp5dCN/bSdkWWWPle4=,iv:Xsu6kX7yNGHoKqvgwMSNHMflkKKabIzSLXZ5fLUzSJs=,tag:3fXQEfzBL43FyCN8Wqy5lQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
