kind: ENC[AES256_GCM,data:KIXBCkZn,iv:nOQZGi5AiEr2NvfS7i3Yesde6O3nYcCKbe4LoqTPqnI=,tag:qB94QIBloRZY53i/NFFJ5g==,type:str]
ansible_user: ENC[AES256_GCM,data:vHb/eg==,iv:RX8JWQIOc1CW6viS2wqwaOGa+mXorUsfLiA69JwfGqY=,tag:+rLWxTYu9C5GqTQSUYGbBg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rroaAA==,iv:ot9GTpzY1hdI5vphvfd/XohESjPDThAGte6Z86o2+V8=,tag:FnU4/4XQ2cfBipsqYXZONw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNnI0V0YvVDBlcFM2am5Q
            SWNKbkV1cDh1UzJLb0lWZk50TlJXWHBmdVZJCldMWGp6Yk9JOU5GTTYzQW9mNjF1
            eXFJM1k0Yk1rck5sOHpqWllOcVBrTW8KLS0tIFBuUEVCUWNxQ044ekUrQ2dVa1JC
            cUgvZDlmQ0Z3MUpTV2tnVnV6WjlrT2MK/qrE+yPZp8IgjzjStbv4h6xQX64hWYT7
            SadtoRz5voQNUeWBg2rfEQK01I3D4ZONZqaobDs+2f1ubFROml6tvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T22:45:24Z"
    mac: ENC[AES256_GCM,data:k3LBuuVcRlJSV9Q9S2BCzwmPDdNwVVKhTUQ0WZUEdVN3R85BNdkBB1ubOL9u72GFKPT5AGyMEpsBF4c07v3vVWH+9+TyoPA5oxwsahBg01wtR82Q0/m6MZh9MfVOXyzD9qtCMopKnhxlHgAWmOOfvcrBeXho3jz1YoPr6ND9Izo=,iv:WBKL6oZNpCpiJc2IOU2+2hQFNNr7aGH6L/8pArCmWuM=,tag:/di5p7aoB0Udl9fXoxIQAg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
