apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:xq8hsjNYPrZ/wefz2Xi/9G67HU1pAMIHsblRPA/mtP689QgPIrvorQ==,iv:iNQXU2HsMRp20+SnzdUd70lZ+NPudHs63W3jO8O3gEk=,tag:mhDKEKoqfPk+7+naJOj1lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQm1aeEZHQ0VXTUtPallz
            SW53Zm5wbllrYTRwZVN5MHh2Q3ZRbUhJbUhnCmxWb0xoMk9PUkF2eEh6OVNKQWdF
            ZTVka0g3M1lrQ1pXU21kMm03YTZEWm8KLS0tIHRzK015UU1JcnBVRGtha2RkOW9z
            Ym1oTkNXckk3STYwNWZ3a3ByaHh0Tk0KyNvKxB4mO52xcV+ytQzzIvUQDzFaVCL+
            PEkcctnGjQ6kmkjoiJb6JngXyJuJ2FuBLimsC088wC3SKr/y5YB7Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T00:11:03Z"
    mac: ENC[AES256_GCM,data:DVuTIEw4WclL/iccH5E4gvCV5ZSmoI2JfIG0xD3702wbSUziqnU1IsSPJy9FtVU5ttsMhoOFmHZC1RMWcBcNbqThp/bcQiu3isNY9/XNlk5ut4CXNKIBmeUQ9tS9SDN//SypamWCKAR5TzJ8rVYAf7rL9NmZVterhi9sXKHN+bM=,iv:k3Woammm/nsXwfmRu81IzaD5O+xnKpg+m0TVSb1iJ7U=,tag:HdcAeFh+gs+ypOyKSi+UgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
