apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:qOBOWNjpHEP/a76l+yNw0YDxYjmFALT25l4LGJdDWpJhVes/oBf/TQ==,iv:8mawfYqwHPidy+f+YNO0LGbKkxLvdlfq53++mvAVPAI=,tag:9cvkElqZAkdyc00/UentxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaTZtL3NBenVZZ1BWbHBL
            NWFLUm10dy85b1E4K1VxMXQ4YTdCZDVUeGx3Ck5yaE8vQWc1RktiSzBpanJUdTVt
            ZXpxSHhLaHVNMVlqTFlIejFrMnlPS0EKLS0tIGJZbnA3WFgwc295cE5ReTRiY1JG
            TWZ0aThYSDRlblFtWStrQTBSazFJbWsKEvEKQczVXRsmtCaNmDrXD4rU8xRmsdWJ
            aRKPScDZhg8pV4a6ttpI0PSpCUOaTK8hYecqod0K1Ar0C2qeocKkvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-03T21:45:56Z"
    mac: ENC[AES256_GCM,data:ND7IRDbtVhAz1rrNMTolsVp8RCg8TT2RjmzMyZS1GR1CsCdnuZfvDQu//KNX3yOO0roiR2AnaHLTkoVAgYa07Veg27P+TSHusJ29lZwlYsHA4IYPPnczR3MxhQgaaCGGP4Bwn2PfnoS2329E0O+1Ah/QNP4hCMLwcrWd/kxnPWI=,iv:+/if1POFn+fy/yPboPouAeQiOC+Lql9046jXK/ni/Hs=,tag:tmp/FJjvNkSUNZ19pHy+YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
