---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.211.55.26
        k8s-1:
          ansible_host: 10.211.55.27
        k8s-2:
          ansible_host: 10.211.55.28
    worker:
      hosts:
        k8s-3:
          ansible_host: 10.211.55.54
        k8s-4:
          ansible_host: 10.211.55.55
        k8s-5:
          ansible_host: 10.211.55.56
