---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.211.55.26
    worker:
      hosts:
        k8s-1:
          ansible_host: 10.211.55.27
        k8s-2:
          ansible_host: 10.211.55.28
