apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:+Nb9OxPXpWznzCjEwsw1x3Em+tVfdlsdquxf8ax3kmPnm3ADQw==,iv:scbSJnuSrtTXT83lQFieWcD70vxEtkKtScT2KGGkcIA=,tag:2JTIpJa3eEw3u8Y9DQDkpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGREIrQ01FTktuYTNkbHNa
            Q01pTnBTak5TQ2p3TzhpUTQwc0lxQXppeVNNCjhzRmJXSWwxOHBTRzFoVEVwc0ZW
            UlJabHhJbVo1SnQ4TTNoelRUNWxJV0UKLS0tIDBVenpka29xd2NuTzRPQUlYRlhh
            SlRkL2JmWUt5NDYxVVluODBHTmQyOEkKV/WtHqaYj4790x0120AMNf8OQZl0SqvG
            62J5npeNZhYaWBwwPXlkrufXSKQIISlh9ejqXAfZDyqI+LF8TRo/BQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T22:45:24Z"
    mac: ENC[AES256_GCM,data:Jst3qTS6zCUBnPkMXkR0T6add2Y+HPt7RFc4Qoq2iBfKWLL01GV/hOSiYe8JsY+G2wf9CsgNVD7qEdP69HdV+yYM3eK0SGSzFzSZidQ9jLAHX7XsPeSXYtu5+1MH2PfuXA4etWfjPX098ixhQy8DJTTkEGouxpZygkZelMCWAtM=,iv:WguQgeIzB+p6xgflWcvCUeGrtJX9Tjzh1uRE89O/GsQ=,tag:tpbeRJp+WqiGFaMUuC6vqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
