apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:k69GKfHaZxnPeCOJZY9Eb+jWLtTkvuESoJ0HIYdhMiwAF+QUvA==,iv:o74p/Fj163G9Jm0IgiGe2fN48IWq1kDqVtVmYWP61Ic=,tag:wuvEz673hqUaB//n5aYzsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUGNyZVJ3ZDFlUzJjSmV3
            WGdYdnQ0QWZyaWRoYTVtWTJTd3lMQm81VFg0CmVZWlY3S3k2WnZnbElrV0sxY01G
            MXpYOGhwZGIvcVNqQlhpSVk4UXV6TmMKLS0tIEVSbGFORW9RUmcrV2x6WGRjbVFO
            bVorRWtDODNPRlBUZHdmV2F3UHEwRUkKSOybCjz1FQ30th5BGuVa7/cIL9pztg9+
            /4IA65CxyAakKcSnSMdWtb+FiviGGCjxRlqekSs4y8jSzuk7jG02TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T22:25:04Z"
    mac: ENC[AES256_GCM,data:r1grlSW4LV18682dgCsL0VzoXwIBu1Sbp2Cd6ufrAaWywMQSdh+9hVEgGs2w8vAcgQjxUZKgtjyKRj2xdvVVRmzDuPk9ndirGGEBWgNipmCNGM1+1Mc9GbOv6qoomE1+5jqSocI6H79vYAH2ldiCsLJgW3X3Io5pungCd4cNa3Q=,iv:addDdnz4hNAf3t1V+WW/lT/3nVUR973Sl5lNrhELrpE=,tag:9qKvYckiaLdvZRIwPNjNtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
