apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:9F37z/WjnQgR7OCV9aTvS0yEvvLPisJMlqou96/Up2NZMrHBsA==,iv:qr4TlqVAeF0r8fmqTx28K3PZMnoE2/dVAER043LBQTk=,tag:6KW4cW1P1sOUiQmeQw7SWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMmNNcklJNVFmcHY2Q3A1
            ZHR4K2E2VGwzMDBZMEJBMnUrK0ViNFhTV0dnClhsbTRvZlNvMHJxRDVKMm1ZZFNS
            eFJMZkl6eVZLb0ZzQTlTUDZVMjlKQWsKLS0tIFNrTXgzSDQ1TjRoTkU1S0VEZ1hL
            Zk1DRFVGbUNWM3RTT3BWOUptRE1aTUkKqgq3ehGUhBw+OPuGUgc3T0E3vATwa0d+
            dqMJWz4VlgbW2z/pd2UJwiG/VyR/QngzJbCnCnC9m/by8s1qHgYvFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-11T01:32:22Z"
    mac: ENC[AES256_GCM,data:TEz2qoBu6/upWHMLlq7cm9SxQLjuWpcYf+8gx/uJyH/MV/id8srBEQ3H+HbGGfQ0d7rGro8sQtF0E3PCTB+HzZq2yjjDxDcseJf3GQdASxqWM00HQKpUklyeBElbtIXO+lEvYSHBFHODif83/6Bz1o6hEpMpxYNsYq/lTyOrA3g=,iv:DdfmJFEgxmuRsjDzMzFSFZb3QSc1tAsTxa6rkMaoLJU=,tag:96Vc5a+anvIW4vjYS6Z2LQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
