apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:gcL3fIZtMQfreR/6U8oKkWh9koW2uI4cSg==,iv:QOxTGre25KRkTVZbC0w7TfcdLmNkM/ybaixmfKrBUx4=,tag:TV8wCZoNsd+UaVNSXkAdyw==,type:str]
    api-key: ENC[AES256_GCM,data:4IuWtM04+gb4Qz9KRKEprmQFQyYi9W2Q4De63AHio9rs2Y7XUw==,iv:ZGt8xYhul1xDazX06Ct+okAZ4wX0QlKa0TQxqYCvZp0=,tag:75QhoiYHzM6+nikGY1ADkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOEU2VnFLUExLZXl1WDdp
            SlJueWtUc2dWOWhSS3JYQ3dYTFVhOTNlVzFjCnoydnhhREFDWmtHMUNiMWJtOG0y
            NzFJYUNBRW0rTTJObllCNGd5S1VCck0KLS0tIHNkK3gwT2xYK1I5aFgyVGo0YzNz
            Q3dONUJXcTBXdU8vYjJxL3UxcVM0TlUKlyoVBykW/0kud+HF5sOVUdbd68/f9IHA
            Iuzo+bDrFvxdiVNjTgy0LmDhG0MFMkC13F7YzQblmsgqi31p0KYPcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-11T01:37:45Z"
    mac: ENC[AES256_GCM,data:KH7f/lRXWPB66fKSWnztGOdDeTvH3Ml7jIvRi1KMmLdOU+stMeVW8DYOvnzs+DniuGo8lLv7ekBGRgYFdveX5ekhn9mImbDYGxJIF8tg83dScoj2LDZGXYoiPBHcOl1fIP3/Bl9sOCChBHMV44lGdxDRev+azVu14UieGjs1K/o=,iv:P8qnZp2HrwjykstuWx6x/v/R/1lV3I0WH0WEAgjgn0E=,tag:/Oq7aZPtWS275wZQcD4AsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
