apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:tqy1Ptlq/u8zfDne1kPBQmfSkMAH2OF8EA==,iv:imjzqqQceJK7Uqi+y6BAh5bJUOSQRHu8/xwu4Yow1RA=,tag:Xta+7iczaGgurm/EQwAsJQ==,type:str]
    api-key: ENC[AES256_GCM,data:LcaLg/g4/Lh5IIkT2zbcLtiZHF0DoMIPhky7YVzJkh4j9tFMcg==,iv:cVdn34zwLVi8CEoE8KXiLl/OuGLNmNpHUdosvikWO4E=,tag:nNjHalpoHNVQeo+H65PSjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZjQ5emczTmEvazVaNHBX
            SE5CS2hYZEhWYWJIRzZsN3FlQUpVUitqbWdBCmJtVkhnUFRYb0FMV3BmQkN6eGhh
            RnhkZGx0dFZwS2Z4MnVOQVVwYlNYNk0KLS0tIHZFVlJrRDFUcEkxcVFNd0RTMDZp
            V0ZZcFp6MDI5K1hRK0dDb3JLY1RlcmMKhjtc97ncEdnd6HiJxHgbT0oTPWBfO3eM
            0pxxAs3IdG/0tWysjh4tApGwbRDLH14xHjugjmZLJN6+6tMnA9FYDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T00:11:02Z"
    mac: ENC[AES256_GCM,data:+M2oXwJ8yVAj1xMw14KvghpajrxAAPjbWOgsxLqK/jVk50J5BEhCro6QUinl/MTRF8SQSMKZW4ovOTKjKSj4u4p6cddJtVHtDflgiBPfVFNq0VtcP9H84+d4ZBgcZKwIyAleUFSefYaAjHeNqsuKenrLwVRR2dXg7Y495tKZOho=,iv:o4uibCUBdQhw2G8f7dB7Q5f6QCixUGp8NH5jZuCZ+tc=,tag:vkzPjYHAfOeRWZ24/xX0Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
