apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:TW0QrDodO0LrZF0McLj6dPQo+EkGg7+ufd136Xq6Gg56u+h5T9WRLdRCrfbEh9gH9w4W/LEDwrwcOiju,iv:UNIRKxjlkjYL6izM907vXNy6kL0tmV09+UeU6jMNDXA=,tag:6QPlE5LjWe2hFNZVaD3Img==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMUtldGtkd2Y3TDBNQnI3
            VXJBUkxCMmU0d3N1d1hrZzNveDNPYUpIODBBClJpWndQYkdKMjJEbDRxdzJpRWtT
            TkJIYkhwUXNiaDZ2YVpOTlhUVHl4bGMKLS0tIEVxTzYrd0hoUzJPaXlWcVZIQ1Za
            L3FIVkxXUkdUaWJ2dFI2cWl0dXdNTHMKv65l+FeTT6PtjYjAUPieEr0ECJ25sB5f
            fnzzYjIkMkW0ZZNIEPYJ+dA0bmuMjkIWeC/dNncMHa3plqflH2yD8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-11T01:37:45Z"
    mac: ENC[AES256_GCM,data:32kEEVBCrxUk2GsjUFU1x4lV3yZUGRr7kv6LhKTyDycDVMiFz8abIo5GegevyQjqHXlti8nFtb6tVd9AKNS32WZssV4C9BsEy7b70miL9VKUrrFPOd1LbH/VBS3noYCpg2nT6Hm0j5DjVMRo8R4Wy1KOtGCSlAv1yypdZ54OugE=,iv:vWqI9VmLws9SAGkP5HOh1lsQIsJ8wQ2EX+JOFUy931U=,tag:Jl9TA5Av2n5YgXcgn5LMMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
