apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:cn3DkviwLwFHKNNkp5/cwnWfrqvrhzP5ae5LOeSF6PpsiAGzEzinm1bXPwc9+82cbeijUfti6LpudHOE,iv:sOkmRjeT2071lhUKdB14T6XsomFS21Hu5SM5swmXtSg=,tag:rI6NvGYPbLT0flW/EJEBkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS1NoUmU3ZjRuTjhhd2oy
            Vy9vVXdILzVneFp1cUhPR2FpaHAybC8vRFdJCk9LR1MycmNXR2htQ1FkY3VKS2RL
            SFdwNEEydUUvUXlWcGp1WE9IYXIyeTAKLS0tIHJkNHlsREtxaTRGOU9zZ2d5V1Ns
            LzRLVk1GWDBjY3c4ZzFzeTE2aWVTQTQKZumNN1lIOXkKyDVdn2cdQEInt+TM3xNC
            +D6xZuuowMwtNPrARYP7ZQNXKWv9XsCFHYBC0i57gMdk9dBuh1AYaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-08T10:22:22Z"
    mac: ENC[AES256_GCM,data:PLcQyZrfvNhMnnNLofRPnDYejLF3MYJIudlU6sjZj/263159gGN/FMv5BZjG3D+Fm9tgULehoVJF1wLYOQRQ2TgprW2NrY8g7WI157V9vKaUYou8IHzgh6kGi6LnUtZG+7vJjuGjL/8lursrxvPncrqUq0eVrZcNfxgtt+0gm9U=,iv:wRe0iZ1ua9ws3jU82ThNK1qTtduiVDdqDv4M6FJQRG4=,tag:CbUiC5uUbZjZogrn0qiHqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
