---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.69.100.201"
  METALLB_LB_RANGE: "10.69.100.100-10.69.100.200"
  METALLB_K8S_GATEWAY_ADDR: "10.69.100.199"
  METALLB_INGRESS_ADDR: "10.69.100.200"
