---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.211.55.99"
  METALLB_LB_RANGE: "10.211.55.100-10.211.55.130"
  METALLB_K8S_GATEWAY_ADDR: "10.211.55.129"
  METALLB_INGRESS_ADDR: "10.211.55.130"
