apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:PX5X/QTX9UTht8Y=,iv:sdWp9gxCciSkV8a0pKKjNd04o3EOJ7xXJ6JE+7nlyiI=,tag:+wxc6iQ6/ukT2oUNuRRIxw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:9OtLoC3v82cxkqWNZE/mGHAjseXHPgpVmg==,iv:aRbYSIFXHP0AMYf61kPt9PhqE7NRGaYzpRYi0N3oI10=,tag:+S0yjM11e1s0TJ2mCyeryw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442kghuh2cwmehxrj633npshvh5a4gedt4rrnmtjtwfywekw6daq45azdw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMTVFJdTMzMWxiaWpMUFdV
            bStNb2RLU2RvbndyWFgwL3NiWWJFQ0JMZzBvCkE5TC9Rek5aS1VPelJ6QkZHcm9k
            OFQzbG14bkRZZDY3eml3M01iSGdhQUkKLS0tIEhRc05WZW9BTFF1Q2IxSnBQa3ZI
            RUYweEpFTG9xMktGK0J3bm5CVnVyK2MKeUS1S2I+a1T5uN4xudOGiCESoHo4SMWb
            osAjF3qwEJGr+vvgGOZ05WaHQOLhZf4sKlDuNZaxtzfIurhEqYkvLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-07T22:45:24Z"
    mac: ENC[AES256_GCM,data:G90ZN9ej2ORYcBfZFUJkMBI2q5rXTFrQKcawC9ZVGna3xkl9ar5JluLYmwen3zvl171uKas9TXrFzm8kt8aVUVU75/CK8SgtbM5yGHimZoEwmpt6hjirHOtzyJk1izrWvXBNrycaiAebq2fH3vpPP7/CT0WhC9pHCZq0qP+g57Q=,iv:jkFas9vBir45hUmWwrXa8KYeuolWF3TEMZkeNmAqlrM=,tag:c2I3Qrb8Zaeu/ZnoxlM+Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
