---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KUBE_VIP_ADDR: "10.69.69.99"
  METALLB_LB_RANGE: "10.69.69.100-10.69.69.130"
  METALLB_K8S_GATEWAY_ADDR: "10.69.69.129"
  METALLB_INGRESS_ADDR: "10.69.69.130"
